name: Assignment about workflow

on:
  push:
    branches:
      - main

jobs:
  read_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository's code
        uses: actions/checkout@v4

      - name: Read and print file content
        run: cat hello.txt